using System.Data; using CertDesk.Models;
namespace CertDesk.Services;
public static class CertificateService
{
 public static DataTable Search(string q="",string status="Все",string type="Все")=>DbUtil.Query(@"SELECT c.id AS ID,c.serial_number AS 'Серийный номер',e.full_name AS 'Владелец',c.signature_type AS 'Тип подписи',a.name AS 'Удостоверяющий центр',COALESCE(t.inventory_number,'') AS 'Токен',strftime('%d.%m.%Y',c.issued_at) AS 'Дата выдачи',strftime('%d.%m.%Y',c.valid_from) AS 'Действует с',strftime('%d.%m.%Y',c.valid_to) AS 'Действует до',CAST(julianday(c.valid_to)-julianday(date('now')) AS INTEGER) AS 'Осталось дней',c.status AS 'Статус',c.purpose AS 'Назначение' FROM certificates c JOIN employees e ON e.id=c.employee_id JOIN authorities a ON a.id=c.authority_id LEFT JOIN tokens t ON t.id=c.token_id WHERE (@q='' OR c.serial_number LIKE @p OR e.full_name LIKE @p OR a.name LIKE @p) AND (@s='Все' OR c.status=@s) AND (@ty='Все' OR c.signature_type=@ty) ORDER BY c.valid_to",DbUtil.P("@q",q),DbUtil.P("@p","%"+q+"%"),DbUtil.P("@s",status),DbUtil.P("@ty",type));
 public static Certificate? GetById(int id){ var t=DbUtil.Query("SELECT * FROM certificates WHERE id=@id",DbUtil.P("@id",id)); return t.Rows.Count==0?null:Map(t.Rows[0]); }
 public static List<Certificate> GetAll(){ var t=DbUtil.Query("SELECT * FROM certificates ORDER BY serial_number"); return t.Rows.Cast<DataRow>().Select(Map).ToList(); }
 static Certificate Map(DataRow r)=>new(){Id=Convert.ToInt32(r["id"]),EmployeeId=Convert.ToInt32(r["employee_id"]),AuthorityId=Convert.ToInt32(r["authority_id"]),TokenId=r["token_id"]==DBNull.Value?null:Convert.ToInt32(r["token_id"]),SerialNumber=Convert.ToString(r["serial_number"])!,SignatureType=Convert.ToString(r["signature_type"])!,IssuedAt=DbUtil.ParseDate(r["issued_at"]),ValidFrom=DbUtil.ParseDate(r["valid_from"]),ValidTo=DbUtil.ParseDate(r["valid_to"]),Status=Convert.ToString(r["status"])!,Purpose=Convert.ToString(r["purpose"]),IsArchived=Convert.ToInt32(r["is_archived"])==1};
 public static int Create(Certificate c,CurrentUser u){ c.Status=StatusService.CalculateCertificateStatus(c.ValidTo,c.Status); var id=Convert.ToInt32(DbUtil.Scalar("INSERT INTO certificates(employee_id,authority_id,token_id,serial_number,signature_type,issued_at,valid_from,valid_to,status,purpose,is_archived) VALUES(@e,@a,@t,@s,@st,@i,@vf,@vt,@status,@p,0) RETURNING id",P(c))); AuditService.Write(u,"создание сертификата","certificates",id,c.SerialNumber); return id; }
 public static void Update(Certificate c,CurrentUser u){ c.Status=StatusService.CalculateCertificateStatus(c.ValidTo,c.Status); DbUtil.Execute("UPDATE certificates SET employee_id=@e,authority_id=@a,token_id=@t,serial_number=@s,signature_type=@st,issued_at=@i,valid_from=@vf,valid_to=@vt,status=@status,purpose=@p WHERE id=@id",P(c).Append(DbUtil.P("@id",c.Id)).ToArray()); AuditService.Write(u,"изменение сертификата","certificates",c.Id,c.SerialNumber); }
 public static void Revoke(int id,CurrentUser u){ DbUtil.Execute("UPDATE certificates SET status='revoked' WHERE id=@id",DbUtil.P("@id",id)); AuditService.Write(u,"отзыв сертификата","certificates",id,"Сертификат отозван"); }
 public static void Archive(int id,CurrentUser u){ DbUtil.Execute("UPDATE certificates SET status='archived', is_archived=1 WHERE id=@id",DbUtil.P("@id",id)); AuditService.Write(u,"архивирование сертификата","certificates",id,"Сертификат архивирован"); }
 public static int CountByStatus(string s)=>Convert.ToInt32(DbUtil.Scalar("SELECT COUNT(*) FROM certificates WHERE status=@s",DbUtil.P("@s",s))??0);
 public static DataTable GetAttentionItems()=>DbUtil.Query(@"SELECT 'Сертификат' AS 'Тип',c.serial_number AS 'Номер',e.full_name AS 'Сотрудник',strftime('%d.%m.%Y',c.valid_to) AS 'Действует до',CAST(julianday(c.valid_to)-julianday(date('now')) AS INTEGER) AS 'Осталось дней',c.status AS 'Статус' FROM certificates c JOIN employees e ON e.id=c.employee_id WHERE c.status IN ('warning','expired')");
 static Microsoft.Data.Sqlite.SqliteParameter[] P(Certificate c)=>new[]{DbUtil.P("@e",c.EmployeeId),DbUtil.P("@a",c.AuthorityId),DbUtil.P("@t",c.TokenId),DbUtil.P("@s",c.SerialNumber),DbUtil.P("@st",c.SignatureType),DbUtil.P("@i",DbUtil.D(c.IssuedAt)),DbUtil.P("@vf",DbUtil.D(c.ValidFrom)),DbUtil.P("@vt",DbUtil.D(c.ValidTo)),DbUtil.P("@status",c.Status),DbUtil.P("@p",c.Purpose)};
}
