using System.Data; using CertDesk.Models;
namespace CertDesk.Services;
public static class MchdService
{
 public static DataTable Search(string q="",string status="Все",string reg="Все")=>DbUtil.Query(@"SELECT m.id AS ID,m.number AS 'Номер МЧД',COALESCE(p.full_name,'') AS 'Доверитель',r.full_name AS 'Представитель',COALESCE(c.serial_number,'') AS 'Сертификат',m.powers AS 'Полномочия',m.powers_codes AS 'Коды полномочий',strftime('%d.%m.%Y',m.valid_from) AS 'Действует с',strftime('%d.%m.%Y',m.valid_to) AS 'Действует до',CAST(julianday(m.valid_to)-julianday(date('now')) AS INTEGER) AS 'Осталось дней',CASE m.is_registered WHEN 1 THEN 'Зарегистрирована' ELSE 'Не зарегистрирована' END AS 'Регистрация',m.status AS 'Статус' FROM mchd m LEFT JOIN employees p ON p.id=m.principal_employee_id JOIN employees r ON r.id=m.representative_employee_id LEFT JOIN certificates c ON c.id=m.certificate_id WHERE (@q='' OR m.number LIKE @p OR r.full_name LIKE @p OR p.full_name LIKE @p) AND (@s='Все' OR m.status=@s) AND (@r='Все' OR (@r='Зарегистрирована' AND m.is_registered=1) OR (@r='Не зарегистрирована' AND m.is_registered=0)) ORDER BY m.valid_to",DbUtil.P("@q",q),DbUtil.P("@p","%"+q+"%"),DbUtil.P("@s",status),DbUtil.P("@r",reg));
 public static Mchd? GetById(int id){ var t=DbUtil.Query("SELECT * FROM mchd WHERE id=@id",DbUtil.P("@id",id)); return t.Rows.Count==0?null:Map(t.Rows[0]); }
 static Mchd Map(DataRow r)=>new(){Id=Convert.ToInt32(r["id"]),Number=Convert.ToString(r["number"])!,PrincipalEmployeeId=r["principal_employee_id"]==DBNull.Value?null:Convert.ToInt32(r["principal_employee_id"]),RepresentativeEmployeeId=Convert.ToInt32(r["representative_employee_id"]),CertificateId=r["certificate_id"]==DBNull.Value?null:Convert.ToInt32(r["certificate_id"]),Powers=Convert.ToString(r["powers"])!,PowersCodes=Convert.ToString(r["powers_codes"]),ValidFrom=DbUtil.ParseDate(r["valid_from"]),ValidTo=DbUtil.ParseDate(r["valid_to"]),IsRegistered=Convert.ToInt32(r["is_registered"])==1,Status=Convert.ToString(r["status"])!,Notes=Convert.ToString(r["notes"])};
 public static int Create(Mchd m,CurrentUser u){ m.Status=StatusService.CalculateMchdStatus(m.ValidTo,m.Status); var id=Convert.ToInt32(DbUtil.Scalar("INSERT INTO mchd(number,principal_employee_id,representative_employee_id,certificate_id,powers,powers_codes,valid_from,valid_to,is_registered,status,notes) VALUES(@n,@p,@r,@c,@pw,@pc,@vf,@vt,@ir,@s,@no) RETURNING id",P(m))); AuditService.Write(u,"создание МЧД","mchd",id,m.Number); return id; }
 public static void Update(Mchd m,CurrentUser u){ m.Status=StatusService.CalculateMchdStatus(m.ValidTo,m.Status); DbUtil.Execute("UPDATE mchd SET number=@n,principal_employee_id=@p,representative_employee_id=@r,certificate_id=@c,powers=@pw,powers_codes=@pc,valid_from=@vf,valid_to=@vt,is_registered=@ir,status=@s,notes=@no WHERE id=@id",P(m).Append(DbUtil.P("@id",m.Id)).ToArray()); AuditService.Write(u,"изменение МЧД","mchd",m.Id,m.Number); }
 public static void Revoke(int id,CurrentUser u){ DbUtil.Execute("UPDATE mchd SET status='revoked' WHERE id=@id",DbUtil.P("@id",id)); AuditService.Write(u,"отзыв МЧД","mchd",id,"МЧД отозвана"); }
 public static void Archive(int id,CurrentUser u){ DbUtil.Execute("UPDATE mchd SET status='archived' WHERE id=@id",DbUtil.P("@id",id)); AuditService.Write(u,"архивирование МЧД","mchd",id,"МЧД архивирована"); }
 public static int CountByStatus(string s)=>Convert.ToInt32(DbUtil.Scalar("SELECT COUNT(*) FROM mchd WHERE status=@s",DbUtil.P("@s",s))??0);
 public static DataTable GetAttentionItems()=>DbUtil.Query(@"SELECT 'МЧД' AS 'Тип',m.number AS 'Номер',e.full_name AS 'Сотрудник',strftime('%d.%m.%Y',m.valid_to) AS 'Действует до',CAST(julianday(m.valid_to)-julianday(date('now')) AS INTEGER) AS 'Осталось дней',m.status AS 'Статус' FROM mchd m JOIN employees e ON e.id=m.representative_employee_id WHERE m.status IN ('warning','expired')");
 static Microsoft.Data.Sqlite.SqliteParameter[] P(Mchd m)=>new[]{DbUtil.P("@n",m.Number),DbUtil.P("@p",m.PrincipalEmployeeId),DbUtil.P("@r",m.RepresentativeEmployeeId),DbUtil.P("@c",m.CertificateId),DbUtil.P("@pw",m.Powers),DbUtil.P("@pc",m.PowersCodes),DbUtil.P("@vf",DbUtil.D(m.ValidFrom)),DbUtil.P("@vt",DbUtil.D(m.ValidTo)),DbUtil.P("@ir",m.IsRegistered?1:0),DbUtil.P("@s",m.Status),DbUtil.P("@no",m.Notes)};
}
