using System.Data; using CertDesk.Data; using CertDesk.Models;
namespace CertDesk.Services;
public static class TokenService
{
 public static DataTable Search(string q="",string status="Все")=>DbUtil.Query(@"SELECT t.id AS ID,t.inventory_number AS 'Инвентарный номер',t.token_type AS 'Тип',t.model AS 'Модель',t.serial_number AS 'Серийный номер',t.status AS 'Статус',COALESCE(e.full_name,'') AS 'Текущий держатель',strftime('%d.%m.%Y',t.received_at) AS 'Дата поступления',t.notes AS 'Примечание' FROM tokens t LEFT JOIN employees e ON e.id=t.holder_id WHERE (@q='' OR t.inventory_number LIKE @p OR t.serial_number LIKE @p OR e.full_name LIKE @p) AND (@s='Все' OR t.status=@s) ORDER BY t.inventory_number",DbUtil.P("@q",q),DbUtil.P("@p","%"+q+"%"),DbUtil.P("@s",status));
 public static List<TokenDevice> GetAll(){ var t=DbUtil.Query("SELECT * FROM tokens ORDER BY inventory_number"); return t.Rows.Cast<DataRow>().Select(Map).ToList(); }
 public static TokenDevice? GetById(int id){ var t=DbUtil.Query("SELECT * FROM tokens WHERE id=@id",DbUtil.P("@id",id)); return t.Rows.Count==0?null:Map(t.Rows[0]); }
 static TokenDevice Map(DataRow r)=>new(){Id=Convert.ToInt32(r["id"]),InventoryNumber=Convert.ToString(r["inventory_number"])!,TokenType=Convert.ToString(r["token_type"])!,Model=Convert.ToString(r["model"]),SerialNumber=Convert.ToString(r["serial_number"]),Status=Convert.ToString(r["status"])!,HolderId=r["holder_id"]==DBNull.Value?null:Convert.ToInt32(r["holder_id"]),ReceivedAt=r["received_at"]==DBNull.Value?null:DbUtil.ParseDate(r["received_at"]),Notes=Convert.ToString(r["notes"])};
 public static int Create(TokenDevice t,CurrentUser u){ var id=Convert.ToInt32(DbUtil.Scalar("INSERT INTO tokens(inventory_number,token_type,model,serial_number,status,holder_id,received_at,notes) VALUES(@i,@ty,@m,@s,@st,@h,@r,@n) RETURNING id",P(t))); AuditService.Write(u,"создание токена","tokens",id,t.InventoryNumber); return id; }
 public static void Update(TokenDevice t,CurrentUser u){ DbUtil.Execute("UPDATE tokens SET inventory_number=@i,token_type=@ty,model=@m,serial_number=@s,status=@st,holder_id=@h,received_at=@r,notes=@n WHERE id=@id",P(t).Append(DbUtil.P("@id",t.Id)).ToArray()); AuditService.Write(u,"изменение токена","tokens",t.Id,t.InventoryNumber); }
 public static void Issue(int id,int emp,string? act,string? comment,CurrentUser u)=>Tx(id,emp,"issue","issued",act,comment,u,true);
 public static void Return(int id,CurrentUser u)=>Tx(id,null,"return","storage",null,"Возврат токена",u,false);
 public static void MarkDamaged(int id,CurrentUser u)=>Tx(id,null,"damage","damaged",null,"Токен поврежден",u,false);
 public static void WriteOff(int id,CurrentUser u)=>Tx(id,null,"write_off","written_off",null,"Токен списан",u,false);
 static void Tx(int id,int? emp,string op,string status,string? act,string? comment,CurrentUser u,bool keepHolder){ using var c=Db.OpenConnection(); using var tr=c.BeginTransaction(); using var cmd=c.CreateCommand(); cmd.Transaction=tr; cmd.CommandText="UPDATE tokens SET status=@s, holder_id=@h WHERE id=@id"; cmd.Parameters.AddWithValue("@s",status); cmd.Parameters.AddWithValue("@h", keepHolder && emp.HasValue ? (object)emp.Value : DBNull.Value); cmd.Parameters.AddWithValue("@id",id); cmd.ExecuteNonQuery(); cmd.Parameters.Clear(); cmd.CommandText="INSERT INTO token_operations(token_id,employee_id,operation,act_number,comment,operator_user_id) VALUES(@t,@e,@o,@a,@c,@u)"; cmd.Parameters.AddWithValue("@t",id); cmd.Parameters.AddWithValue("@e", emp.HasValue ? (object)emp.Value : DBNull.Value); cmd.Parameters.AddWithValue("@o",op); cmd.Parameters.AddWithValue("@a",act??(object)DBNull.Value); cmd.Parameters.AddWithValue("@c",comment??(object)DBNull.Value); cmd.Parameters.AddWithValue("@u",u.Id); cmd.ExecuteNonQuery(); tr.Commit(); AuditService.Write(u,op switch{"issue"=>"выдача токена","return"=>"возврат токена","damage"=>"повреждение токена",_=>"списание токена"},"tokens",id,comment); }
 public static DataTable GetOperations()=>DbUtil.Query(@"SELECT o.id AS ID,t.inventory_number AS 'Токен',COALESCE(e.full_name,'') AS 'Сотрудник',o.operation AS 'Операция',o.act_number AS 'Акт',o.comment AS 'Комментарий',strftime('%d.%m.%Y %H:%M',o.created_at) AS 'Дата' FROM token_operations o JOIN tokens t ON t.id=o.token_id LEFT JOIN employees e ON e.id=o.employee_id ORDER BY o.id DESC");
 public static int CountAll()=>Convert.ToInt32(DbUtil.Scalar("SELECT COUNT(*) FROM tokens")??0); public static int CountIssued()=>Convert.ToInt32(DbUtil.Scalar("SELECT COUNT(*) FROM tokens WHERE status='issued'")??0);
 static Microsoft.Data.Sqlite.SqliteParameter[] P(TokenDevice t)=>new[]{DbUtil.P("@i",t.InventoryNumber),DbUtil.P("@ty",t.TokenType),DbUtil.P("@m",t.Model),DbUtil.P("@s",string.IsNullOrWhiteSpace(t.SerialNumber)?null:t.SerialNumber),DbUtil.P("@st",t.Status),DbUtil.P("@h",t.HolderId),DbUtil.P("@r",t.ReceivedAt.HasValue?DbUtil.D(t.ReceivedAt.Value):null),DbUtil.P("@n",t.Notes)};
}
